version: '3'
services:
  cte_federated_trainer:
    build:
      context: ./
      dockerfile: './federated_trainer/Dockerfile'
    container_name: cte_federated_trainer
    ports:
       - "8080:8080"
    networks:
      - backend
  cte_data_owner:
    build:
      context: ./
      dockerfile: './data_owner/Dockerfile'
    ports:
     - "5000"
     - "3000-3100:3000"
    networks:
      - backend
    depends_on:
      - cte_federated_trainer
  cte_model_buyer:
    build:
      context: ./
      dockerfile: './model_buyer/Dockerfile'
    ports:
     - "9090:9090"
    networks:
      - backend
networks:
  backend:
