version: '3'
services:
  cte_federated_trainer:
    build:
      context: ./
      dockerfile: './server/Dockerfile'
    container_name: cte_federated_trainer
    ports:
       - "8080:8080"
    networks:
      - backend
  cte_data_owner:
    build:
      context: ./
      dockerfile: './client/Dockerfile'
    ports:
     - "5000"
    networks:
      - backend
    depends_on:
      - cte_federated_trainer
networks:
  backend:
