version: '3'
services:
  cte_server:
    build:
      context: ./
      dockerfile: './server/Dockerfile'
    container_name: cte_server
    ports:
       - "8080:8080"
    networks:
      - backend
  cte_client:
    build:
      context: ./
      dockerfile: './client/Dockerfile'
    ports:
     - "5000"
    networks:
      - backend
    depends_on:
      - cte_server
networks:
  backend:
